language: node_js
node_js:
  - '18'
  - '17'
  - '16'  
  - '15'      
  - '14'
  - '13'
  - '12'
  - '11'
  - '10'
script:
  - npm run test:standard
  - npm run test:coverage
after_success:
  - npm run report:coverage
